# Generated by Django 2.1.7 on 2019-04-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drafter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('bot', models.BooleanField()),
                ('bot_state', models.BinaryField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.Draft')),
            ],
        ),
    ]
