# Generated by Django 2.1.7 on 2019-04-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_auto_20190407_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafter',
            name='current_phase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drafter',
            name='current_pick',
            field=models.IntegerField(default=0),
        ),
    ]
