# Generated by Django 2.1.7 on 2019-04-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0004_auto_20190407_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='cards_per_pack',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='num_drafters',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='num_phases',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
