# Generated by Django 2.1.7 on 2019-04-07 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0005_auto_20190407_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drafts.Drafter'),
        ),
    ]
