# Generated by Django 2.1.7 on 2019-04-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0006_auto_20190407_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='picked_at',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
