# Generated by Django 2.1.7 on 2019-04-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0007_card_picked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='picked_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
