# Generated by Django 3.0.3 on 2020-04-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0008_auto_20190407_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafter',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
