# Generated by Django 3.0.3 on 2020-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0009_drafter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='cube_id',
            field=models.IntegerField(default=81183),
            preserve_default=False,
        ),
    ]
