"Azorius Signet" = "UW"
"Boros Signet" = "RW"
"Dimir Signet" = "BU"
"Golgari Signet" = "BG"
"Gruul Signet" = "GR"
"Izzet Signet" = "RU"
"Orzhov Signet" = "BW"
"Rakdos Signet" = "BR"
"Selesnya Signet" = "GW"
"Simic Signet" = "GU"
"Adarkar Wastes" = "UW"
"Glacial Fortress" = "UW"
"Irrigated Farmland" = "UW"
"Seachrome Coast" = "UW"
"Darkslick Shores" = "BU"
"Drowned Catacomb" = "BU"
"Fetid Pools" = "BU"
"Underground River" = "BU"
"Blackcleave Cliffs" = "BR"
"Canyon Slough" = "BR"
"Dragonskull Summit" = "BR"
"Sulfurous Springs" = "BR"
"Copperline Gorge" = "GR"
"Karplusan Forest" = "GR"
"Rootbound Crag" = "GR"
"Sheltered Thicket" = "GR"
Brushland = "GW"
"Razorverge Thicket" = "GW"
"Scattered Groves" = "GW"
"Sunpetal Grove" = "GW"
"Caves of Koilos" = "BW"
"Concealed Courtyard" = "BW"
"Isolated Chapel" = "BW"
"Temple of Silence" = "BW"
"Blooming Marsh" = "BG"
"Llanowar Wastes" = "BG"
"Temple of Malady" = "BG"
"Woodland Cemetery" = "BG"
"Botanical Sanctum" = "GU"
"Hinterland Harbor" = "GU"
"Temple of Mystery" = "GU"
"Yavimaya Coast" = "GU"
"Shivan Reef" = "RU"
"Spirebluff Canal" = "RU"
"Sulfur Falls" = "RU"
"Temple of Epiphany" = "RU"
"Battlefield Forge" = "RW"
"Clifftop Retreat" = "RW"
"Inspiring Vantage" = "RW"
"Temple of Triumph" = "RW"

