"Arid Mesa" = "RW"
"Blood Crypt" = "BR"
"Bloodstained Mire" = "BR"
"Breeding Pool" = "GU"
"Cascade Bluffs" = "RU"
"Celestial Colonnade" = "UW"
"Clifftop Retreat" = "RW"
"Creeping Tar Pit" = "BU"
"Dragonskull Summit" = "BR"
"Drowned Catacomb" = "BU"
"Fetid Heath" = "BW"
"Fire-Lit Thicket" = "GR"
"Flooded Grove" = "GU"
"Flooded Strand" = "UW"
"Glacial Fortress" = "UW"
"Godless Shrine" = "BW"
"Graven Cairns" = "BR"
"Hallowed Fountain" = "UW"
"Hinterland Harbor" = "GU"
"Hissing Quagmire" = "BG"
"Isolated Chapel" = "BW"
"Lavaclaw Reaches" = "BR"
"Lumbering Falls" = "GU"
"Marsh Flats" = "BW"
"Misty Rainforest" = "GU"
"Mystic Gate" = "UW"
"Needle Spires" = "RW"
"Overgrown Tomb" = "BG"
"Polluted Delta" = "BU"
"Raging Ravine" = "GR"
"Rootbound Crag" = "GR"
"Rugged Prairie" = "RW"
"Sacred Foundry" = "RW"
"Scalding Tarn" = "RU"
"Shambling Vent" = "BW"
"Steam Vents" = "RU"
"Stirring Wildwood" = "GW"
"Stomping Ground" = "GR"
"Sulfur Falls" = "RU"
"Sunken Ruins" = "BU"
"Sunpetal Grove" = "GW"
"Temple Garden" = "GW"
"Temple of Epiphany" = "RU"
"Temple of Malady" = "BG"
"Temple of Mystery" = "GU"
"Temple of Silence" = "BW"
"Temple of Triumph" = "RW"
"Twilight Mire" = "BG"
"Verdant Catacombs" = "BG"
"Wandering Fumarole" = "RU"
"Watery Grave" = "BU"
"Windswept Heath" = "GW"
"Wooded Bastion" = "GW"
"Wooded Foothills" = "GR"
"Woodland Cemetery" = "BG"
"Irrigated Farmland" = "UW"
"Fetid Pools" = "BU"
"Canyon Slough" = "BR"
"Sheltered Thicket" = "GR"
"Scattered Groves" = "GW"
