"Arid Mesa" = "RW"
"Ash Barrens" = "BRGUW"
"Blackcleave Cliffs" = "BR"
"Blood Crypt" = "BR"
"Bloodstained Mire" = "BR"
"Boros Garrison" = "RW"
"Breeding Pool" = "GU"
"Cascade Bluffs" = "RU"
"Celestial Colonnade" = "UW"
"Clifftop Retreat" = "RW"
"Copperline Gorge" = "GR"
"Creeping Tar Pit" = "BU"
"Darkslick Shores" = "BU"
"Fetid Heath" = "BW"
"Fire-Lit Thicket" = "GR"
"Flooded Grove" = "GU"
"Flooded Strand" = "UW"
"Godless Shrine" = "BW"
"Graven Cairns" = "BR"
"Hallowed Fountain" = "UW"
"Hinterland Harbor" = "GU"
"Hissing Quagmire" = "BG"
"Isolated Chapel" = "BW"
"Izzet Boilerworks" = "RU"
"Lavaclaw Reaches" = "BR"
"Lumbering Falls" = "GU"
"Marsh Flats" = "BW"
"Misty Rainforest" = "GU"
"Mystic Gate" = "UW"
"Needle Spires" = "RW"
"Overgrown Tomb" = "BG"
"Polluted Delta" = "BU"
"Raging Ravine" = "GR"
"Rakdos Carnarium" = "BR"
"Razorverge Thicket" = "GW"
"Rugged Prairie" = "RW"
"Sacred Foundry" = "RW"
"Scalding Tarn" = "RU"
"Seachrome Coast" = "UW"
"Shambling Vent" = "BW"
"Steam Vents" = "RU"
"Stirring Wildwood" = "GW"
"Stomping Ground" = "GR"
"Sulfur Falls" = "RU"
"Sunken Ruins" = "BU"
"Temple Garden" = "GW"
"Temple of Abandon" = "GR"
"Temple of Deceit" = "BU"
"Temple of Enlightenment" = "UW"
"Temple of Malady" = "BG"
"Temple of Mystery" = "GU"
"Temple of Plenty" = "GW"
"Temple of Silence" = "BW"
"Twilight Mire" = "BG"
"Verdant Catacombs" = "BG"
"Wandering Fumarole" = "RU"
"Watery Grave" = "BU"
"Windswept Heath" = "GW"
"Wooded Bastion" = "GW"
"Wooded Foothills" = "GR"
"Woodland Cemetery" = "BG"
