"Celestial Colonnade" = "UW"
"Glacial Fortress" = "UW"
"Hallowed Fountain" = "UW"
"Mystic Gate" = "UW"
"Temple of Enlightenment" = "UW"
"Creeping Tar Pit" = "BU"
"Drowned Catacomb" = "BU"
"Sunken Ruins" = "BU"
"Temple of Deceit" = "BU"
"Watery Grave" = "BU"
"Blood Crypt" = "BR"
"Dragonskull Summit" = "BR"
"Graven Cairns" = "BR"
"Lavaclaw Reaches" = "BR"
"Temple of Malice" = "BR"
"Fire-Lit Thicket" = "GR"
"Raging Ravine" = "GR"
"Rootbound Crag" = "GR"
"Stomping Ground" = "GR"
"Temple of Abandon" = "GR"
"Stirring Wildwood" = "GW"
"Sunpetal Grove" = "GW"
"Temple Garden" = "GW"
"Temple of Plenty" = "GW"
"Wooded Bastion" = "GW"
"Fetid Heath" = "BW"
"Godless Shrine" = "BW"
"Isolated Chapel" = "BW"
"Shambling Vent" = "BW"
"Temple of Silence" = "BW"
"Hissing Quagmire" = "BG"
"Overgrown Tomb" = "BG"
"Temple of Malady" = "BG"
"Twilight Mire" = "BG"
"Woodland Cemetery" = "BG"
"Breeding Pool" = "GU"
"Flooded Grove" = "GU"
"Hinterland Harbor" = "GU"
"Lumbering Falls" = "GU"
"Temple of Mystery" = "GU"
"Cascade Bluffs" = "RU"
"Steam Vents" = "RU"
"Sulfur Falls" = "RU"
"Temple of Epiphany" = "RU"
"Wandering Fumarole" = "RU"
"Clifftop Retreat" = "RW"
"Needle Spires" = "RW"
"Rugged Prairie" = "RW"
"Sacred Foundry" = "RW"
"Temple of Triumph" = "RW"
"Arid Mesa" = "RW"
"Bloodstained Mire" = "BR"
"Flooded Strand" = "UW"
"Marsh Flats" = "BW"
"Misty Rainforest" = "GU"
"Polluted Delta" = "BU"
"Scalding Tarn" = "RU"
"Verdant Catacombs" = "BG"
"Windswept Heath" = "GW"
"Wooded Foothills" = "GR"