"Adarkar Wastes" = "UW"
"Azorius Chancery" = "UW"
"Port Town" = "UW"
"Temple of Enlightenment" = "UW"
"Choked Estuary" = "BU"
"Dimir Aqueduct" = "BU"
"Temple of Deceit" = "BU"
"Underground River" = "BU"
"Foreboding Ruins" = "BR"
"Rakdos Carnarium" = "BR"
"Sulfurous Springs" = "BR"
"Temple of Malice" = "BR"
"Game Trail" = "GR"
"Gruul Turf" = "GR"
"Karplusan Forest" = "GR"
"Temple of Abandon" = "GR"
Brushland = "GW"
"Fortified Village" = "GW"
"Selesnya Sanctuary" = "GW"
"Temple of Plenty" = "GW"
"Caves of Koilos" = "BW"
"Orzhov Basilica" = "BW"
"Shineshadow Snarl" = "BW"
"Temple of Silence" = "BW"
"Frostboil Snarl" = "RU"
"Izzet Boilerworks" = "RU"
"Shivan Reef" = "RU"
"Temple of Epiphany" = "RU"
"Golgari Rot Farm" = "BG"
"Llanowar Wastes" = "BG"
"Necroblossom Snarl" = "BG"
"Temple of Malady" = "BG"
"Battlefield Forge" = "RW"
"Boros Garrison" = "RW"
"Furycalm Snarl" = "RW"
"Temple of Triumph" = "RW"
"Simic Growth Chamber" = "GU"
"Temple of Mystery" = "GU"
"Vineglimmer Snarl" = "GU"
"Yavimaya Coast" = "GU"
"Seaside Citadel" = "GUW"
"Arcane Sanctum" = "BUW"
"Crumbling Necropolis" = "BRU"
"Savage Lands" = "BGR"
"Jungle Shrine" = "GRW"
"Nomad Outpost" = "BRW"
"Frontier Bivouac" = "GRU"
"Sandsteppe Citadel" = "BGW"
"Mystic Monastery" = "RUW"
"Opulent Palace" = "BGU"
"Ash Barrens" = ""

