"Adarkar Wastes" = "UW"
"Azorius Chancery" = "UW"
"Glacial Fortress" = "UW"
"Seachrome Coast" = "UW"
"Darkslick Shores" = "BU"
"Dimir Aqueduct" = "BU"
"Drowned Catacomb" = "BU"
"Underground River" = "BU"
"Blackcleave Cliffs" = "BR"
"Dragonskull Summit" = "BR"
"Rakdos Carnarium" = "BR"
"Sulfurous Springs" = "BR"
"Copperline Gorge" = "GR"
"Gruul Turf" = "GR"
"Karplusan Forest" = "GR"
"Rootbound Crag" = "GR"
Brushland = "GW"
"Razorverge Thicket" = "GW"
"Selesnya Sanctuary" = "GW"
"Sunpetal Grove" = "GW"
"Caves of Koilos" = "BW"
"Concealed Courtyard" = "BW"
"Isolated Chapel" = "BW"
"Orzhov Basilica" = "BW"
"Izzet Boilerworks" = "RU"
"Shivan Reef" = "RU"
"Spirebluff Canal" = "RU"
"Sulfur Falls" = "RU"
"Blooming Marsh" = "BG"
"Golgari Rot Farm" = "BG"
"Llanowar Wastes" = "BG"
"Woodland Cemetery" = "BG"
"Battlefield Forge" = "RW"
"Boros Garrison" = "RW"
"Clifftop Retreat" = "RW"
"Inspiring Vantage" = "RW"
"Botanical Sanctum" = "GU"
"Hinterland Harbor" = "GU"
"Simic Growth Chamber" = "GU"
"Yavimaya Coast" = "GU"
"Seaside Citadel" = "GUW"
"Arcane Sanctum" = "BUW"
"Crumbling Necropolis" = "BRU"
"Savage Lands" = "BGR"
"Jungle Shrine" = "GRW"
"Nomad Outpost" = "BRW"
"Frontier Bivouac" = "GRU"
"Sandsteppe Citadel" = "BGW"
"Mystic Monastery" = "RUW"
"Opulent Palace" = "BGU"

