"Vivid Meadow" = "W"
"Vivid Creek" = "U"
"Vivid Marsh" = "B"
"Vivid Crag" = "R"
"Vivid Grove" = "G"
"Prophetic Prism" = ""
"Sphere of the Suns" = ""
"Adarkar Wastes" = "UW"
"Azorius Chancery" = "UW"
"Deserted Beach" = "UW"
"Temple of Enlightenment" = "UW"
"Dimir Aqueduct" = "BU"
"Shipwreck Marsh" = "BU"
"Temple of Deceit" = "BU"
"Underground River" = "BU"
"Haunted Ridge" = "BR"
"Rakdos Carnarium" = "BR"
"Sulfurous Springs" = "BR"
"Temple of Malice" = "BR"
"Gruul Turf" = "GR"
"Karplusan Forest" = "GR"
"Rockfall Vale" = "GR"
"Temple of Abandon" = "GR"
Brushland = "GW"
"Overgrown Farmland" = "GW"
"Selesnya Sanctuary" = "GW"
"Temple of Plenty" = "GW"
"Caves of Koilos" = "BW"
"Orzhov Basilica" = "BW"
"Shattered Sanctum" = "BW"
"Temple of Silence" = "BW"
"Izzet Boilerworks" = "RU"
"Shivan Reef" = "RU"
"Stormcarved Coast" = "RU"
"Temple of Epiphany" = "RU"
"Deathcap Glade" = "BG"
"Golgari Rot Farm" = "BG"
"Llanowar Wastes" = "BG"
"Temple of Malady" = "BG"
"Battlefield Forge" = "RW"
"Boros Garrison" = "RW"
"Sundown Pass" = "RW"
"Temple of Triumph" = "RW"
"Dreamroot Cascade" = "GU"
"Simic Growth Chamber" = "GU"
"Temple of Mystery" = "GU"
"Yavimaya Coast" = "GU"
"Seaside Citadel" = "GUW"
"Arcane Sanctum" = "BUW"
"Crumbling Necropolis" = "BRU"
"Savage Lands" = "BGR"
"Jungle Shrine" = "GRW"
"Nomad Outpost" = "BRW"
"Frontier Bivouac" = "GRU"
"Sandsteppe Citadel" = "BGW"
"Mystic Monastery" = "RUW"
"Opulent Palace" = "BGU"
"Aether Hub" = ""
"Fabled Passage" = ""
"Mirrodin's Core" = ""

