"Adarkar Wastes" = "UW"
"Celestial Colonnade" = "UW"
"Flood Plain" = ""
"Irrigated Farmland" = "UW"
"Mystic Gate" = "UW"
"Port Town" = "UW"
"Prairie Stream" = "UW"
"Bad River" = ""
"Choked Estuary" = "BU"
"Creeping Tar Pit" = "BU"
"Fetid Pools" = "BU"
"Sunken Hollow" = "BU"
"Sunken Ruins" = "BU"
"Underground River" = "BU"
"Canyon Slough" = "BR"
"Foreboding Ruins" = "BR"
"Graven Cairns" = "BR"
"Lavaclaw Reaches" = "BR"
"Rocky Tar Pit" = ""
"Smoldering Marsh" = "BR"
"Sulfurous Springs" = "BR"
"Cinder Glade" = "GR"
"Fire-Lit Thicket" = "GR"
"Game Trail" = "GR"
"Karplusan Forest" = "GR"
"Mountain Valley" = ""
"Raging Ravine" = "GR"
"Sheltered Thicket" = "GR"
Brushland = "GW"
"Canopy Vista" = "GW"
"Fortified Village" = "GW"
Grasslands = ""
"Scattered Groves" = "GW"
"Stirring Wildwood" = "GW"
"Wooded Bastion" = "GW"
"Caves of Koilos" = "BW"
"Concealed Courtyard" = "BW"
"Fetid Heath" = "BW"
"Shambling Vent" = "BW"
"Shineshadow Snarl" = "BW"
"Temple of Silence" = "BW"
"Cascade Bluffs" = "RU"
"Frostboil Snarl" = "RU"
"Shivan Reef" = "RU"
"Spirebluff Canal" = "RU"
"Temple of Epiphany" = "RU"
"Wandering Fumarole" = "RU"
"Blooming Marsh" = "BG"
"Hissing Quagmire" = "BG"
"Llanowar Wastes" = "BG"
"Necroblossom Snarl" = "BG"
"Temple of Malady" = "BG"
"Twilight Mire" = "BG"
"Battlefield Forge" = "RW"
"Furycalm Snarl" = "RW"
"Inspiring Vantage" = "RW"
"Needle Spires" = "RW"
"Rugged Prairie" = "RW"
"Temple of Triumph" = "RW"
"Botanical Sanctum" = "GU"
"Flooded Grove" = "GU"
"Lumbering Falls" = "GU"
"Temple of Mystery" = "GU"
"Vineglimmer Snarl" = "GU"
"Yavimaya Coast" = "GU"
"Savai Triome" = "BRW"
"Ketria Triome" = "GRU"
"Indatha Triome" = "BGW"
"Raugrin Triome" = "RUW"
"Zagoth Triome" = "BGU"
"Ash Barrens" = ""
"Evolving Wilds" = ""
"Fabled Passage" = ""
"Prismatic Vista" = ""
"Terramorphic Expanse" = ""

