"Adarkar Wastes" = "UW"
"Celestial Colonnade" = "UW"
"Deserted Beach" = "UW"
"Hallowed Fountain" = "UW"
"Port Town" = "UW"
"Temple of Enlightenment" = "UW"
"Choked Estuary" = "BU"
"Creeping Tar Pit" = "BU"
"Shipwreck Marsh" = "BU"
"Temple of Deceit" = "BU"
"Underground River" = "BU"
"Watery Grave" = "BU"
"Blood Crypt" = "BR"
"Foreboding Ruins" = "BR"
"Haunted Ridge" = "BR"
"Lavaclaw Reaches" = "BR"
"Sulfurous Springs" = "BR"
"Temple of Malice" = "BR"
"Game Trail" = "GR"
"Karplusan Forest" = "GR"
"Raging Ravine" = "GR"
"Rockfall Vale" = "GR"
"Stomping Ground" = "GR"
"Temple of Abandon" = "GR"
Brushland = "GW"
"Fortified Village" = "GW"
"Overgrown Farmland" = "GW"
"Stirring Wildwood" = "GW"
"Temple Garden" = "GW"
"Temple of Plenty" = "GW"
"Caves of Koilos" = "BW"
"Concealed Courtyard" = "BW"
"Godless Shrine" = "BW"
"Shambling Vent" = "BW"
"Shineshadow Snarl" = "BW"
"Temple of Silence" = "BW"
"Frostboil Snarl" = "RU"
"Shivan Reef" = "RU"
"Spirebluff Canal" = "RU"
"Steam Vents" = "RU"
"Temple of Epiphany" = "RU"
"Wandering Fumarole" = "RU"
"Blooming Marsh" = "BG"
"Hissing Quagmire" = "BG"
"Llanowar Wastes" = "BG"
"Necroblossom Snarl" = "BG"
"Overgrown Tomb" = "BG"
"Temple of Malady" = "BG"
"Battlefield Forge" = "RW"
"Furycalm Snarl" = "RW"
"Inspiring Vantage" = "RW"
"Needle Spires" = "RW"
"Sacred Foundry" = "RW"
"Temple of Triumph" = "RW"
"Botanical Sanctum" = "GU"
"Breeding Pool" = "GU"
"Lumbering Falls" = "GU"
"Temple of Mystery" = "GU"
"Vineglimmer Snarl" = "GU"
"Yavimaya Coast" = "GU"
"Ash Barrens" = ""
"Fabled Passage" = ""
"Prismatic Vista" = ""

