"Adarkar Wastes" = "UW"
"Azorius Signet" = "UW"
"Battlefield Forge" = "RW"
"Boros Signet" = "RW"
Brushland = "GW"
"Canyon Slough" = "BR"
"Caves of Koilos" = "BW"
"Cinder Barrens" = "BR"
"Clifftop Retreat" = "RW"
"Dimir Signet" = "BU"
"Dragonskull Summit" = "BR"
"Drowned Catacomb" = "BU"
"Fetid Pools" = "BU"
"Forsaken Sanctuary" = "BW"
"Foul Orchard" = "BG"
"Glacial Fortress" = "UW"
"Golgari Signet" = "BG"
"Gruul Signet" = "GR"
"Highland Lake" = "RU"
"Hinterland Harbor" = "GU"
"Irrigated Farmland" = "UW"
"Isolated Chapel" = "BW"
"Izzet Signet" = "RU"
"Karplusan Forest" = "GR"
"Llanowar Wastes" = "BG"
"Meandering River" = "UW"
"Orzhov Signet" = "BW"
"Rakdos Signet" = "BR"
"Rootbound Crag" = "GR"
"Scattered Groves" = "GW"
"Selesnya Signet" = "GW"
"Sheltered Thicket" = "GR"
"Shivan Reef" = "RU"
"Simic Signet" = "GU"
"Stone Quarry" = "RW"
"Submerged Boneyard" = "BU"
"Sulfur Falls" = "RU"
"Sulfurous Springs" = "BR"
"Sunpetal Grove" = "GW"
"Temple of Epiphany" = "RU"
"Temple of Malady" = "BG"
"Temple of Mystery" = "GU"
"Temple of Silence" = "BW"
"Temple of Triumph" = "RW"
"Timber Gorge" = "GR"
"Tranquil Expanse" = "GW"
"Underground River" = "BU"
"Woodland Cemetery" = "BG"
"Woodland Stream" = "GU"
"Yavimaya Coast" = "GU"
